name: Build and deploy Node.js project to Azure Function App - atamagri-api

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'
      - '.github/workflows/master_atamagri-api.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './api'
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 'Resolve Project Dependencies Using Npm'
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          npm install
          npm run build --if-present
          npm prune --production

      - name: Zip artifact for deployment
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../function-app.zip . -x "*.git*" "*.vscode*" "local.settings.json"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: function-app
          path: function-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: function-app

      - name: 'Deploy to Azure Function App'
        id: deploy-to-function-app
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'atamagri-api'
          slot-name: 'Production'
          package: 'function-app.zip'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
